---
- name: Verify Blackbox Exporter Installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Get installed nginx version
      ansible.builtin.command: nginx -v
      register: nginx_version
      changed_when: false
      failed_when: nginx_version.rc != 0

    - name: Assert that nginx version is 1.18
      ansible.builtin.assert:
        that:
          - "'nginx/1.18' in nginx_version.stderr"
        fail_msg: "Nginx version is not 1.18"
